### ISSUE TITLE
BHoM_Adapter: refactoring-UpdateProperty (Public method)- reconsider usage

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#109]
As introduced in https://github.com/BHoM/BHoM_Adapter/issues/87

# Proposals

## 1. Remove UpdateProperty

A first proposal was to completely remove the Public Adapter Method `UpdateProperty `.

### Reasons
- The Push should already take care of Updating Properties.
- Anything extra should be taken care of from the Diffing Engine.
- Lack of implementation by adapters.
- It has never been used by anyone.

## 2. Keep the update property as part of https://github.com/BHoM/BHoM_Adapter/issues/123

@IsakNaslundBh has recently found a possible use to the component. This means that it could be left as it is as part of https://github.com/BHoM/BHoM_Adapter/issues/123

See also https://github.com/BHoM/BHoM_Adapter/issues/135

**Comment by IsakNaslundBh** [comment]
To respond to this:

I think my use case might be better off covered in the push anyway, so do not have anything against removing UpdateProperty in its current state. The case I could think off would require a complete refresh of this anyway

**Comment by alelom** [comment]
I decided to remove the UpdateProperty Public Adapter method in https://github.com/BHoM/BHoM_Adapter/pull/151,

In short, for the following reasons:
- UpdateProperty is strictly speaking a CRUD method, that we expose among the Adapter Actions (Push, Pull, etc) only as an exception
- UpdateProperty (Public Adapter Action) is currently works with FilterRequests and making it compliant would require some work
- The best fit I see for his use is the Push method anyway
