### ISSUE TITLE
BHoM_Adapter: refactoring-remove ErrorLog in light of the Global error system

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#113]
### Description
The Global Error system should now replace the old error log.

### Error log usage analysis
![image](https://user-images.githubusercontent.com/6352844/60672681-e3ae8500-9e6d-11e9-9cc3-2d15e788b2a6.png)

### Related PRs
Will be ticked once merged:
- [x] https://github.com/BHoM/GSA_Toolkit/pull/116
- [ ] https://github.com/BHoM/ETABS_Toolkit/pull/216
- [x] https://github.com/BHoM/TAS_Toolkit/pull/216

**Comment by JosefTaylor** [comment]
Got rid of the offending method entirely:
https://github.com/BHoM/ETABS_Toolkit/pull/216
