### ISSUE TITLE
BHoM_Adapter: Mapping Ids to newObjects does not work correctly for dependent objects

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_Adapter#134]
#### Description:

When pushing an object that has a dependent object, the mapping of the dependent objects does not map all of the ids. Taking the case below:

1. Push two `Bar` objects using the Replace() method
2. `newObjects` are two distinct bars 
3. `dependencyObject` is `SteelSection` and runs the `Replace()` method again for the two `SteelSection` objects
4. `newObjects` is a single `SteelSection`, 
5. `dependencyObject` is a `Material` and runs the `Replace()` method for a single `Material` object
6.  Assigns Id to the `Material` object
7. Maps the Id back to `objectsToPush` (which is only one `Material` object)
8. Assigns Id to the `SteelSection` object
9. Maps Id to the `objectsToPush` (which is two `SteelSection` objects) but fails to map the dependency Id

This results in an error because when the `Bar` is to be pushed, because the `Material` that is assigned to it has no Id stored. 

#### How to replicate:

1. Create one `SteelSection` and assign one `Material` 
2. Create two `Bar` objects and assign the `SteelSection`
3. Try to push the `Bar` using a toolkit that makes use of the dependency types

#### Expected behaviour:

No error to occur when pushing a bar with assigned dependencies.

A fix can be found by changing the input used for dependency objects by using `objectsToPush` rather than `newObjects` as the distinct method is going to be called at the start of the Replace method anyway. @IsakNaslundBh @alelom @FraserGreenroyd to discuss, will this have an impact on performance?
```
// Merge and push the dependencies
if (Config.SeparateProperties)
{
    var dependencyObjects = GetDependencyObjects<T>(objectsToPush, tag);

    foreach (var depObj in dependencyObjects)
        if (!Replace(depObj.Value as dynamic, tag))
            return false;
}
```

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/ErcnwvYD2WFPhxygE9UQEQUBKf5ZCE8qwwB1UB8lObNieA?e=6yYoE6

### Additional comments
- The issue does not arise in the Robot_Toolkit, this is likely due to the `SectionProperty` owning a Material and therefore a distinct `SectionProperty `being pushed and assigned to a `Bar`.
- Whereas the Lusas_Toolkit the Material and `SectionProperty `are distinct properties of a `Bar`, therefore when pushing a `Bar `object, the `AdapterID `is required to identify the `Material `assigned

**Comment by peterjamesnugent** [comment]
As discussed with @alelom:
- We carried out a test using the v2.3.alpha.11i installer (dated June 26th 2019) which was prior to any refactoring changes
- The functionality works using the current build of the MidasCivil_Toolkit with the v2.3.alpha.11i installer
- Therefore, a change has been made in the BHoM_Adapter that results in the bug described above, likely in the refactoring
- The issue does not arise in the Robot_Toolkit, this is likely due to the `SectionProperty` owning a Material and therefore a distinct `SectionProperty `being pushed and assigned to a `Bar`.
- Whereas the MidasCivil_Toolkit + Lusas_Toolkit the Material and `SectionProperty `are distinct properties of a `Bar`, therefore when pushing a `Bar `object, the `AdapterID `is required to identify the `Material `assigned

Actions:
- Test if the suggested change in  `var dependencyObjects = GetDependencyObjects<T>(newObjects, tag);`  to `var dependencyObjects = GetDependencyObjects<T>(objectsToPush, tag);`has a significant impact on performance
- Test for 10, 100 and 1000 bar objects where all `Bar `objects will have the same `SectionProperty` a `Material`) so it tests the mapping of Ids to the `objectsToPush`
- Determine if there is an alternate way to map dependent object Ids

**Comment by IsakNaslundBh** [comment]
Had a quick look into this now as well @peterjamesnugent and I think you are right, we need to change from `newObject` to `objectsToPush`.

This happened due to a change the way the cloning is being made, going from shallow cloning level by level with reassignment to full on deepcloning. I think this change was needed in general, but the consequence is that we will need to do what you are suggesting here.

An alternative is to update the pushed host objects to always point to the object that actually went into the adapter. But would defenitely update as suggested ASAP.
