### ISSUE TITLE
BHoM_Adapter: Define Strategy for adapters versions

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Adapter#137]
#### Broken rules:
There is currently no well defined strategy on how to handle multiple version of APis. See for example ETABS and Revit. The approaches are quite different and need to be formalised.

**Comment by al-fisher** [comment]
@epignatelli has recently implemented an approach for Rhinoceros too.

**Comment by adecler** [comment]
Closing as this issue is now over 3 years old.
@alelom , please reopen if it is still relevant
