### ISSUE TITLE
BHoM_Adapter: File_Adapter should not reside in this repo

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#152]
#### Broken rules:
BHoM_Adapter solution should not contain another adapter.

There are historical reasons for having it there, but we should now strive for compliance, especially in the Adapter.

#### Suggestions to restore compliance:

Create a separate repo for the File_Adapter.

We can also rename the File_Adapter to something more appropriate, like JSON_Adapter (if it wasn't  for the fact that it can also write to BSON). 

Questions are: 
1. Do we need/does it make sense to keep the BSON functionality there? I have never personally used it.
2. Should I keep the name File_Adapter or not when creating the new Repo? If the BSON functionality was not there, we could rename the adapter JSON_Adapter, to keep it consistent with the naming of e.g. CSV_Adapter, XML_Adapter, etc.

Eventually, I think we should strive to merge the JSON/CSV (and possibly the XML too) in one Toolkit only. For the time being, I think the highest priority is move out the File_Adapter from the BHoM_Adapter, then we can see.

@adecler @IsakNaslundBh @al-fisher @epignatelli

**Comment by adecler** [comment]
Agreed. 

I would keep the name as File_Adapter as it is not about the format we are using but WHERE we are sending the data.

I am not sure what you mean by keeping the Bson functionality. Do you mean providing the option to either save in human-readable or binary format ? In that case, I see that as a good feature, no?

On a side note, it might be a good time to start considering the format we are using to save the data. By that I mean one object per line. It would probably preferable to use the Dataset object instead so we can benefit from the additional information it contains.

**Comment by alelom** [comment]
Following our conversation on the HTTP as well, this might become part of a "Protocol_Toolkit" or something similar in the future.

**Comment by FraserGreenroyd** [comment]
Given File_Toolkit exists, and File_Adapter is no longer in this repo, I am closing this issue.
