### ISSUE TITLE
Public adapter method Delete (and UI component) to be renamed "Remove"

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#156]
The ["Public Adapter Method" Delete](https://github.com/BHoM/BHoM_Adapter/blob/9d3ea2111d94123007905222f319ea044b2cd4a7/BHoM_Adapter/BHoMAdapter.cs#L172) is the method called by the UI Delete component.
It should be renamed to "Remove" or something else that clarifies that it is _not_ a CRUD method per se to avoid confusion.

The confusion is amplified by its default implementation, that only returns a call to the actual CRUD delete:
https://github.com/BHoM/BHoM_Adapter/blob/9d3ea2111d94123007905222f319ea044b2cd4a7/BHoM_Adapter/BHoMAdapter.cs#L172-L175

A rename would be beneficial for the following reasons:

1. It would be consistent with our philosophy of not exposing CRUD methods directly in the UI, unlike now (especially in light of the fact that I deleted the UpdateProperty component for the same reason, which is a good consistency improvement IMHO).
1. The fact that its default implementation only returns a call to the CRUD delete is only a side-effect of being a _default_ implementation. You can always override the Delete component without affecting the CRUD Delete.
1.  The public method _should in principle_ be called something different than the CRUD Delete because it has all rights to implement additional functionality other than the CRUD Delete strictly speaking
1. **While reviewing the BHoM_Adapter refactoring level03, I realised how confusing is to understand when an Adapter is overriding the actual CRUD Delete or when it's overriding the Delete component method**

If we all agree, I will action this in the Level04 refactoring, where other script-breaking changes will happen.

@adecler @IsakNaslundBh @al-fisher @epignatelli

**Comment by adecler** [comment]
While I was not too keen when reading the title, you're making a few good points. As far as I am concerned, it is even more important to make sure that the BHoM is clear and intuitive for the end user than for the few people creating the adapters. As long as "Remove" is well understood and accepted on the end user side, I fine with this idea.

**Comment by adecler** [comment]
I think this comment says it all 😄 : https://github.com/BHoM/Mongo_Toolkit/pull/78#issuecomment-548645690
