### ISSUE TITLE
Execute to return both a `bool success` and an `object result`

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#175]
#### Description:

After a discussion with @rwemay and @al-fisher , it emerged a new use case for Execute to return not only a `bool`, but also a `System.Object` object that can contain whatever result might come out of the command execution.

**Comment by IsakNaslundBh** [comment]
I think this should be fine and generally better

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/GSA_Toolkit/commit/62dfa4c22cdc82cb4f20e0d96b6782c3fc6209a2
