### ISSUE TITLE
Common approach to pushing/pulling meta objects

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Adapter#177]
#### Description:

Would be good to define a common approach (if there isn't one already!) to exchanging larger objects, those that contain many elements etc. We have a multistorey object and a truss object which have lists of elements, at the moment these need to be unwrapped in the UI and pushed. The short-term/easy option is to simply add another convert, but I wonder if there's a meta tag, or series of interfaces that let us categorize a bit further, then unwrap methods in the adapter to dispatch to relevant converts.

**Comment by alelom** [comment]
I would say this could be solved/connected to #341!
