### ISSUE TITLE
BHoM_Adaptor : MapSpecialProperties HelperMethods review

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Adapter#19]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
This has been significantly rewritten and is now using adapter modules. Think this can be closed out.

@al-fisher please feel free to open if you disagree!

**Comment by alelom** [comment]
Thanks @IsakNaslundBh
