### ISSUE TITLE
I want to implement an Adapter. What do I need to know / look at?

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/BHoM_Adapter#197]
I want to implement an Adapter. What do I need to know / look at?

**Comment by rwemay** [comment]
#dontpanic

What kind of adapter? ;-)

**Comment by rolyhudson** [comment]
Just for OpenStreetMap_Toolkit for pulling data as response from query

**Comment by alelom** [comment]
Let's have a chat on Skype.

**Comment by rolyhudson** [comment]
incredible response times!! 👍

**Comment by rwemay** [comment]
@alelom beat me to it, was going to say have a chat.

**Comment by alelom** [comment]
Hopefully our chat should have clarified things. Just for reference, I'm including some useful links here:
https://github.com/BHoM/documentation/wiki/The-Adapter-Interface 
https://github.com/BHoM/documentation/wiki/The-BHoM-Toolkit 
 
Feel free to close this if that's enough :)
Thanks

**Comment by rolyhudson** [comment]
🤣 The solution to the question.... Is you don't need to implement an adapter here. 😆 
HTTP_Adapter will handle this soon. And in the short term keep using HTTP.Compute.GetRequest. 
Just need a review and approval on this PR: https://github.com/BHoM/HTTP_Toolkit/pull/35 to make sure HTTP.Compute.GetRequest is marked as deprecated and changed back to public to temporarily allow the request.
