### ISSUE TITLE
Compliance issues

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Adapter#202]
The following compliance issues have been found for this repository. Please see the checklist below.
#### Compliance issue for InputAttributeStartsLower
 - [x] Input attribute should start with a lowercase letter in BHoM_Adapter\Adapter_Engine\Modify\CopyBHoMObjectProperties.cs at line 40, column 82 

#### Compliance issue for NameMatchesFileName
 - [x] Method name must match file name in BHoM_Adapter\Adapter_Engine\Query\GetModules.cs at line 35, column 53 

#### Compliance issue for ModifyReturnsSameType
 - [ ] Modify methods must return the same type as their first parameter in BHoM_Adapter\Adapter_Engine\Modify\CopyBHoMObjectProperties.cs at line 40, column 22 
 - [ ] Modify methods must return the same type as their first parameter in BHoM_Adapter\Adapter_Engine\Modify\WrapNonBHoMObjects.cs at line 36, column 22

**Comment by alelom** [comment]
@FraserGreenroyd  we need to add exceptions for the ModifyReturnsSameType: it does not cover when the method returns void because it modifies inputs by reference.

**Comment by alelom** [comment]
So after discussion with @FraserGreenroyd and @awakeman :

- We don't allow modify by ref in engine methods to ensure no backward propagation happens ever (even if you could be deepcloning inside to protect)

- In the case of `CopyBHoMObjectProperties()`, we need to change the return type from void to `T`, return `target`, and deepcopying to protect the modification by ref.
