### ISSUE TITLE
Change Adapter oM and Engine namespaces to `Adapters`

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#213]
## Description 
See the [general issue text below](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-597186509).

## Action required
The repos that need attention are **all Toolkits that include an Adapter project**.

- [ ] https://github.com/BHoM/3DRepo_Toolkit (not in installer) @alelom 
- [x] https://github.com/BHoM/DIALux_Toolkit
- [ ] https://github.com/BHoM/EnergyPlus_Toolkit (not in installer)
- [ ] https://github.com/BHoM/HTTP_Toolkit
- [x] https://github.com/BHoM/IES_Toolkit
- [x] https://github.com/BHoM/Lusas_Toolkit @peterjamesnugent  [PR](https://github.com/BHoM/Lusas_Toolkit/pull/240)
- [x] https://github.com/BHoM/MidasCivil_Toolkit @peterjamesnugent  [PR](https://github.com/BHoM/MidasCivil_Toolkit/pull/203)
- [x] https://github.com/BHoM/Mongo_Toolkit
- [ ] https://github.com/BHoM/OpenStudio_Toolkit (not in installer)
- [ ] https://github.com/BHoM/OpenStreetMap_Toolkit
- [x] https://github.com/BHoM/RAM_Toolkit no action needed
- [x] https://github.com/BHoM/Revit_Toolkit @pawelbaran (I think this is https://github.com/BHoM/Revit_Toolkit/issues/517)
- [x] https://github.com/BHoM/RFEM_Toolkit https://github.com/BHoM/RFEM_Toolkit/pull/86
- [x] https://github.com/BHoM/Robot_Toolkit https://github.com/BHoM/Robot_Toolkit/pull/380
- [x] https://github.com/BHoM/ETABS_Toolkit https://github.com/BHoM/ETABS_Toolkit/pull/319
- [x] https://github.com/BHoM/GSA_Toolkit https://github.com/BHoM/GSA_Toolkit/pull/179
- [ ] https://github.com/BHoM/SAP2000_Toolkit
- [ ] https://github.com/BHoM/S-Frame_Toolkit (not in installer)
- [x] https://github.com/BHoM/Socket_Toolkit
- [ ] https://github.com/BHoM/Speckle_Toolkit  (not in installer)  @alelom 
- [x] https://github.com/BHoM/TAS_Toolkit
- [ ] https://github.com/BHoM/TeklaStructuralDesigner_Toolkit
- [x] https://github.com/BHoM/XML_Toolkit @FraserGreenroyd [PR](https://github.com/BHoM/XML_Toolkit/pull/442)

**Comment by alelom** [comment]
# Description
This Toolkit might require some changes to existing namespaces.

Make the following changes for all your **definitions** that fall in a namespace like shown below.

Note that the following **`using`s**:
```cs
using BH.oM.Adapter;
```
```cs
using BH.Engine.Adapter;
```
are **not to be changed** as they refer to the base adapter namespace, which is not the subject of the current renaming.

## Changes needed:

> - oM:
>    - BH.oM.Adapters.Revit -> must become BH.oM.External.Revit
>    - BH.oM.Adapter.GSA -> must become BH.oM.External.GSA
>    - BH.oM.Adapter.Dynamo -> must become BH.oM.External.Dynamo

> - Engine:
>    - BH.Engine.Adapters.Revit -> must become BH.Engine.External.Revit
>    - BH.Engine.Adapter.GSA -> must become BH.Engine.External.GSA

**Comment by alelom** [comment]
## Files that need attention

### https://github.com/BHoM/3DRepo_Toolkit
TDRepo_Adapter/TDRepoAdapter.cs
### https://github.com/BHoM/Lusas_Toolkit
Lusas_Adapter/LusasAdapter.cs
Lusas_Adapter/CRUD/Read/Read.cs
Lusas_Adapter/CRUD/Delete/Delete.cs
Lusas_Adapter/LusasAdapter.cs
Lusas_Adapter/Type/NextFreeId.cs
Lusas_Adapter/CRUD/Create/Properties/LineMesh.cs
### https://github.com/BHoM/Mongo_Toolkit
Mongo_Adapter/AdapterActions/Execute.cs
### https://github.com/BHoM/RAM_Toolkit
RAM_Adapter/AdapterActions/Pull.cs
RAM_Adapter/Types/Comparer.cs
### https://github.com/BHoM/Revit_Toolkit
Revit_Adapter/AdapterActions/Remove.cs
Revit_Adapter/RevitAdapter.cs
Adapter_Revit_UI/RevitUIAdapter.cs
Revit_UI/RevitListener.cs
Revit_Engine/Query/IsValid.cs
Revit_Engine/Query/Discipline.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/BHoMObject.cs
Engine_Revit_UI/Query/BuiltInCategory.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/IInstance.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/DraftingInstance.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/Family.cs
Revit_Engine/Modify/SetFamilyTypeName.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByInts.cs
Adapter_Revit_UI/RevitUIAdapter.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/ViewPlan.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByCategoryName.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByParameterExistence.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByTemplate.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByViewType.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByWorksets.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsViewTemplate.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsEnergyAnalysisModel.cs
Engine_Revit_UI/Query/RevitTypes.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByDBType.cs
Engine_Revit_UI/Convert/ToRevit.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/Viewport.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/InstanceProperties.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByUniqueIds.cs
Adapter_Revit_UI/AdapterActions/Push.cs
Engine_Revit_UI/Modify/SetIdentifiers.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/InstanceProperties.cs
Adapter_Revit_UI/Modify/SetIdentifiers.cs
Engine_Revit_UI/Query/BuiltInCategory.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/BHoMObject.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/IInstance.cs
Engine_Revit_UI/Query/Family.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/DraftingInstance.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/ViewPlan.cs
Adapter_Revit_UI/CRUD/Read.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByInts.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByUniqueIds.cs
Engine_Revit_UI/Compute/LoadFamilySymbol.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByDBType.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/Sheet.cs
Engine_Revit_UI/Convert/Revit/ToBHoM/Viewport.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByCategoryName.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByParameterExistence.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByTemplate.cs
Engine_Revit_UI/Query/ElementIds/ElementIdsByViewType.cs
### https://github.com/BHoM/Robot_Toolkit
Robot_Adapter/CRUD/Update/Elements/Nodes.cs
Robot_Adapter/CRUD/Update/Loads/Loadcases.cs
Robot_Adapter/CRUD/Update/Loads/LoadCombinations.cs
Robot_Adapter/CRUD/Update/Properties/LinkConstraints.cs
Robot_Adapter/CRUD/Update/Properties/SectionProperties.cs
Robot_Adapter/CRUD/Create/Create.cs
Robot_Adapter/Types/Comparer.cs
Robot_Adapter/CRUD/Create/Create.cs
Robot_Engine/Create/GeometricLineLoad.cs
Robot_Engine/Create/ContourLoad.cs
Robot_Adapter/CRUD/Read/Elements/DesignGroups.cs
Robot_Engine/Create/GeometricLineLoad.cs
Robot_Engine/Create/ContourLoad.cs
### https://github.com/BHoM/TAS_Toolkit
TAS_TBDAdapter/TASTBDAdapter.cs
TAS_TSDAdapter/TASTSDAdapter.cs
TAS_TBDAdapter/TASTBDAdapter.cs
### https://github.com/BHoM/TeklaStructuralDesigner_Toolkit
TeklaStructuralDesigner_Adapter/TeklaStructuralDesignerAdapter.cs
### https://github.com/BHoM/Test_Toolkit
InteroperabilityTest_Engine/Compute/PushPullCompare.cs
### https://github.com/BHoM/XML_Toolkit
XML_Adapter/XMLAdapter.cs
XML_Adapter/XMLSerializer.cs
XML_Adapter/CRUD/Create.cs
XML_Adapter/XMLAdapter.cs

**Comment by alelom** [comment]
After last chat with @al-fisher 

We decided to bump this as a priority in 3.2

Reason is, to get best compromise between the benefit of the renaming and the actual amount of work, we thought it's best to properly change all existing Adapter-based-Toolkits.

I'm including updated instructions above.

**Comment by rwemay** [comment]
Apart from the vote for `BH.oM.Adapters` (plural), I'm just going to throw one final curved ball in there - `BH.oM.Adaptation`.

**Comment by IsakNaslundBh** [comment]
My vote goes to `BH.oM.Adapters`

**Comment by epignatelli** [comment]
I also updated the wiki for the `External` class to specify what that is about:
https://github.com/BHoM/documentation/wiki/BHoM_Engine-Classes/

My vote goes to `Adaptation`.

**Comment by alelom** [comment]
Everyone,
thanks for the nice chat!

I'd like everyone to express their preference in this survey:
https://www.surveymonkey.co.uk/r/BHGQYX3

**Comment by pawelbaran** [comment]
True democracy!

**Comment by rwemay** [comment]
:) I bottled it and went with my initial instinct of adapters plural. Looks like adapters wins?! Let’s reserve adaptation for truly chameleon like behaviours!

**Comment by alelom** [comment]
![image](https://user-images.githubusercontent.com/6352844/81929554-1fae8c80-95df-11ea-9b7c-8b648f3d6d8c.png)
Official results for the joy of democratation 😄

**Comment by alelom** [comment]
Updated issue title and [instructions](https://github.com/BHoM/BHoM_Adapter/issues/213#issuecomment-597186509)

**Comment by FraserGreenroyd** [comment]
Can I confirm that this is now the absolute latest version that we're going with? Cause XML Toolkit has already changed to External and will now need updating again, and MidasCivil/Lusas have gone to External by @peterjamesnugent and will presumably also need updating - so would like to avoid making the change again if the decision is not concrete? Definitely `BH.Engine.Adapters.Blah` for  anything we don't want exposed in UIs?

**Comment by pawelbaran** [comment]
Hitting up @FraserGreenroyd's query - happy to action but could we please confirm we all are aligned?

**Comment by peterjamesnugent** [comment]
@pawelbaran I've already made the changes on MidasCivil and Lusas.

**Comment by pawelbaran** [comment]
Changes to `External` or `Adapters`?

**Comment by peterjamesnugent** [comment]
`Adapters`

**Comment by al-fisher** [comment]
Yes - can confirm `Adapters` is agreed namespace following all discussions

@alelom

**Comment by alelom** [comment]
Yes it is `Adapters`.

**Comment by alelom** [comment]
Closing as completed.
