### ISSUE TITLE
BHoM_Adapter: Consistency in Requests for Pull and Remove

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Adapter#239]
#### Description:

If one tries to Pull with this FilterRequest 
![image](https://user-images.githubusercontent.com/53530468/86237508-ca7d0900-bb93-11ea-9a27-5712c226d262.png)

It works fine, but trying the same for Remove does not work.
As Delete in the BHoM_Adapter disregards the filterRequests elementids and tries to find it owns (from the tags)

Would like similar way to use the requests for both Pull and Remove as they are quite similar from a users point of view.

**Comment by alelom** [comment]
Linked to https://github.com/BHoM/BHoM_Adapter/issues/247

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/BHoM_Adapter/pull/264
