### ISSUE TITLE
BHoM_Adapter: Automatic wrapping into a FilterRequest does not work on Remove

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Adapter#247]
#### Description:

Pull component can accept a bare `Type` argument that is wrapped into a `FilterRequest` automatically. Similar behaviour would be welcome for `Remove`.

![image](https://user-images.githubusercontent.com/26874773/93215918-56e8a200-f767-11ea-87c9-7c659b2f50c7.png)

**Comment by alelom** [comment]
Sounds good. This is an item for next beta. We should refactor the FilterRequest, splitting their functionality in a TypeRequest and anything else needed. Then I'd like to simply add an `implicit` cast from Type to TypeRequest, to cover cases like these without having to propagate and duplicate functionality. 
I'll keep this in mind. Thanks @pawelbaran .

**Comment by pawelbaran** [comment]
> This is an item for next beta.

Sure, that is why I marked it as a feature 👍 Absolutely no rush, it is a 100% nice to have.

**Comment by alelom** [comment]
Linked to https://github.com/BHoM/BHoM_Adapter/issues/239

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/BHoM_Adapter/pull/264
