### ISSUE TITLE
File_Adapter: Handling of geometry primitives

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Adapter#249]
#### Description:

Currently if one wants to save a geometry to file, it seems to require hacks and workarounds due to the fact that geometries are not `BHoMObjects`. Without wrapping it simply does not work, while with `WrapNonBHoMObjects` setting set to true, the geometries pushed from GH come in as wrapped Rhino objects, not wrapped BHoM geometries. Although I see the reason for that on the code level, it does not make much sense from the user's perspective.

Following the above, I would consider implementing some workaround that would handle BHoM geometry primitives same as `BHoMObjects`, so that the script in the screenshot below was functional OOTB:

![image](https://user-images.githubusercontent.com/26874773/94414367-90180d80-017c-11eb-8cab-8a06f1df9f42.png)

I was not sure where to log that particular issue, so put it in the general Adapter - please feel free to transfer if you find applicable.

FYI @IsakNaslundBh @al-fisher @adecler @LMarkowski

**Comment by alelom** [comment]
The new [File_Toolkit](https://github.com/BHoM/File_Toolkit/tree/master/File_oM) that replace the old File_Adapter in this Toolkit does not have this problem. Closing.
