### ISSUE TITLE
Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Adapter#262]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] BHoM_Adapter\AdapterActions\_PushMethods\CRUDDispatchers\CreateOnly.cs

 - [ ] BHoM_Adapter\AdapterActions\_PushMethods\CRUDDispatchers\FullCRUD.cs

 - [ ] BHoM_Adapter\AdapterActions\_PushMethods\ExternalId\AssignId.cs

 - [ ] BHoM_Adapter\CRUD\IDelete.cs

 - [ ] BHoM_Adapter\CRUD\IUpdate.cs

 - [ ] BHoM_Adapter\HelperMethods\CopyBHoMObjectProperties.cs

 - [ ] BHoM_Adapter\File_Adapter\CRUD\Delete.cs

 - [ ] BHoM_Adapter\File_Adapter\CRUD\Read.cs

</p>
</details>

**Comment by alelom** [comment]
Closed by https://github.com/BHoM/BHoM_Adapter/pull/263
