### ISSUE TITLE
Adapter_oM: ActionConfig to store a ComparisonConfig instead of DiffingConfig

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#271]
#### Broken rules:

The only property needed by the Adapter is ComparisonConfig.
Should be fixed urgently as this should solve the Versioning on all ActionConfigs.

**Comment by alelom** [comment]
After our conversation, the scenario where this can actually be an issue is only when the ActionConfig is manually serialized/deserialized (ToString) and/or internalised into a Grasshopper component.

I have checked that all ActionConfigs remain correctly placed on the canvas when a script written in 3.3 is opened in 4.0:

Script file: 

### Script written and seen in v3.3
<details>

![complete script](https://user-images.githubusercontent.com/6352844/102207858-90e05600-3ec6-11eb-9e53-f0f154ae0b58.png)

</details>

### Same script opened in 4.0

<details>

![complete script](https://user-images.githubusercontent.com/6352844/102209860-51673900-3ec9-11eb-9428-626bd2ebcebd.png)

</details>

The DiffConfig is upgraded to DiffingConfig in all instances. 
This means the severity of this issue can be reduced significantly.

**Comment by pawelbaran** [comment]
Just tested, I confirm the autogenerated constructors created in 3.3 work fine on 4.0, I believe we should be OK without a custom converter 👍

**Comment by alelom** [comment]
Ok, closing for now then.

**Comment by alelom** [comment]
Problem: by saving a grasshopper script with ActionConfigs instantiated with auto-created initializers in 4.0, an error appears

![image](https://user-images.githubusercontent.com/6352844/102597589-ca0d0600-4112-11eb-9788-2d3b3ed45e0b.png)

The strange thing is that this does not happen consistently for all ActionConfigs – some just work, e.g. Lusas, PullGeometryConfig and PullRepresentationConfig.

See all ActionConfigs here:

<details>

![ActionConfiginitializers](https://user-images.githubusercontent.com/6352844/102597509-ad70ce00-4112-11eb-967f-24644b8aaecc.png)

</details>

**Comment by alelom** [comment]
> Problem: by saving a grasshopper script with ActionConfigs instantiated with auto-created initializers in 4.0, an error appears

This seems to be a UX problem:
- All ActionConfigs return a valid output even with the Error appearing.  
- Re-enabling the component removes the error message.
