### ISSUE TITLE
Adapter_Engine: AdapterId Query having grasshopper problems

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM_Adapter#283]
#### Description:
`BH.Adapter.Engine.Query.AdapterId(this IBHoMObject bHoMObject, Type adapterIdFragmentType)` doesn't pop up properly on the grasshopper canvas when coming from the ctrl+shift+b search

This might be a grasshopper_UI problem, but given that no other components seem to have the problem, I thought I'd start here.

#### Steps to reproduce:

open grasshopper, ctrl+shift+b search for "adapter query" - two identical options pop up. Click either one to place on the canvas, and the result is a blank query component with the warning message "this is a magic component ..."
![image](https://user-images.githubusercontent.com/7024203/104366263-1a477000-54e7-11eb-8ed0-2a8fcb2db550.png)
![image](https://user-images.githubusercontent.com/7024203/104366311-2b907c80-54e7-11eb-91dd-049d072c77b9.png)

interestingly, you can get to the method by placing a query and then selecting the AdapterId query.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Adapter/%23283-AdapterIdComponent.gh?csf=1&web=1&e=9FPfwb

**Comment by FraserGreenroyd** [comment]
@JosefTaylor can you confirm the last version of the BHoM you installed and if anyone else in your sphere is experiencing the same issue?

**Comment by JosefTaylor** [comment]
I'm running 210112_BuroHappold_BHoM_v4.1.alpha, and @maryannewachter is having the same issue.

**Comment by peterjamesnugent** [comment]
I am having the same issue on today's 210120 installer - I've also found once you've placed the component on the canvas and reopen the script it reverts back to a magic component.

**Comment by adecler** [comment]
It should have been fixed by this PR: https://github.com/BHoM/BHoM_Adapter/pull/290. 
I just tried it and the component is indeed created correctly for me.

Can you check that it works for you too ?

**Comment by peterjamesnugent** [comment]
@adecler works for me too, both using the test script and from the search menu.
