### ISSUE TITLE
Have new Test build configuration and adjust build events to avoid `xcopy` requirement when testing

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM_Adapter#345]
#### Description:

Our `xcopy` mechanism that centralises compiled DLLs requires to have all software that load the compiled DLLs (e.g. Rhino) to be closed at compile time, or the build will fail. This is generally desiderable, but it becomes an inconvenience when doing TDD (Test Driven Development), because you may have e.g. Rhino instance open with large models that you do not want to close just to run VS Unit tests, or an Excel spreadsheet you're using for something else. 

Proposing here to have a different Build Configuration called `Test` that can be used when running Visual Studio tests; the build events can detect it before invoking `xcopy`, as below:

```
if not "$(ConfigurationName)" == "Test" (xcopy "$(TargetDir)$(TargetFileName)" "C:\ProgramData\BHoM\Assemblies" /Y)
```

I'm also investigating whether we could setup a `.runsettings` configuration file for Visual Studio test run, which could default the build configuration to `Test` when the test are run. However, I could not find any info on that so far, and it could be the target of a separate issue.

@FraserGreenroyd @al-fisher

**Comment by FraserGreenroyd** [comment]
This SGTM @alelom - key to capture for the documentation we need to write around this following this mornings workshop.
