### ISSUE TITLE
BHoM_Adapter: Review the ErrorLog in the light of the Global error system

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Adapter#43]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by alelom** [comment]
Following a chat with @IsakNaslundBh, I've included this issue in the Adapter's general refactoring #84.

Generally, the idea would be to get rid of the `ErrorLog` property altogether, replacing any call to it with calls to the `Engine.Reflection` error log mechanism. The less properties in the Adapter, the better.

**Comment by alelom** [comment]
Reopened as https://github.com/BHoM/BHoM_Adapter/issues/113
