### ISSUE TITLE
BHoM_Adapter: use IExecuteParams interface for the Execute command -- enable as config option

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Adapter#45]
To enable more flexible config.

Move the AdapterConfig to the BHoM and make it a BHoMObject

**Comment by adecler** [comment]
@alelom , moving this issue to you as you are currently working on this.

**Comment by alelom** [comment]
Confirmed, this is included in level 04 refactoring.

The formerly named `AdapterConfig` is now called `ActionConfig` (as it is related to adapter *Actions*, i.e. Push, Pull, Execute, etc.) and is in the `BH.oM.Adapter` namespace, included in the `Adapter_oM` project of the BHoM_Adapter solution.
