### ISSUE TITLE
BHoM_Adapter: Pushing BHoM objects within customData for objects with dependencies

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Adapter#47]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by alelom** [comment]
@rwemay is this still relevant? I had a look at the history of this, seems like something which is either superseded by fragments or a case we should not really be covering as part of the framework philosophy.

**Comment by rwemay** [comment]
Not sure! Let's close this issue for now. Can always reopen/create new, but I suspect you're right - a long way out of date now.
