### ISSUE TITLE
BHoM_Adapter: Strategy for formalising CustomData in the case of Software Adapters

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Adapter#49]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by alelom** [comment]
Now covered by Fragments.
