### ISSUE TITLE
BHoM_Adapter: Setting what action to take if same object is found in model

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Adapter#67]
JosefTaylor had a case where he had pre-prepared all section properties in an Etabs model, and wanted to be able to push a set of bars with dummy sections with the correct name and then have them being picked up to the ones already defined in Etabs.

The default behaviour of the adapter is to always take what is being pushed as gospel, always overriding whatever has been created in the model.

Think this need to be controllable from the push setting or something similar, to enable greater flexibility.

**Comment by alelom** [comment]
To me this could be seen as a `CreateOnly` config in the Push component. A boolean that controls whether if an object is already existing, it's simply skipped (no Delete-Create or Update).
@IsakNaslundBh what do you think? If so I could tie this with the refactoring quite nicely.

**Comment by IsakNaslundBh** [comment]
@alelom I think this is slightly different.

What this is referring to is what will happen to elements in the intersection of the venndiagram. Right now the default is for them to get updated, while this would be a config saying "do not touch them". Basically, anything in the intersection would be left as-is in the model.

**Comment by alelom** [comment]
Makes sense. So this will become a `Replace` method where only the `Create` and `Delete` methods are invoked.

**Comment by IsakNaslundBh** [comment]
Solved by https://github.com/BHoM/BHoM_Adapter/pull/205
