### ISSUE TITLE
BHoM_Adapter: Only read on push if tag or Comparer

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Adapter#79]
The `Replace` method in the BHoMAdapter only need to read existing objects if the tag provided != "" OR provided comparer != from the default one, as no action needs to be/can be taken if this is not true.

Should add a check before reading in existing objects. 

This could mean a significant speed boost when pushing a small set of high level objects to a model with a lot of data in it.

**Comment by alelom** [comment]
Closed via https://github.com/BHoM/BHoM_Adapter/pull/103
