### ISSUE TITLE
BHoM_Adapter: Can not pull object

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM_Adapter#80]
I can not pull object back

I can push to JSON
![image](https://user-images.githubusercontent.com/26113670/55953008-eaed3a80-5c52-11e9-8df4-7d14a058ded1.png)
see attached exported file [01_138 Flatbed Teaching_90P.zip](https://github.com/BHoM/BHoM_Adapter/files/3068314/01_138.Flatbed.Teaching_90P.zip)

but when I try to pull this file, it does not work
![image](https://user-images.githubusercontent.com/26113670/55953129-3869a780-5c53-11e9-8586-8d5dc5f69698.png)

**Comment by alelom** [comment]
@michaldengusiak seems this was abandoned. At that time I had recently joined and could not look into this. Is this solved? Can I close it? Do you still need support?

**Comment by alelom** [comment]
I have quickly tested and could not replicate from the information given.
Please feel free to raise a new issue if you find the problem persists

**Comment by michaldengusiak** [comment]
I just tested this again and still  can not pull 

![image](https://user-images.githubusercontent.com/26113670/60646111-631e6300-9e32-11e9-9f78-dd792b88b63f.png)

![image](https://user-images.githubusercontent.com/26113670/60646092-54d04700-9e32-11e9-97ca-c6d8fc8eb513.png)

**Comment by michaldengusiak** [comment]
export works fine
![image](https://user-images.githubusercontent.com/26113670/60646348-125b3a00-9e33-11e9-93d2-06fdc1d95ef0.png)

**Comment by alelom** [comment]
It's because you didn't input a `request` in the Pull component (formerly known as `query`).

![image](https://user-images.githubusercontent.com/6352844/60652942-f9f21c00-9e40-11e9-8507-f771f7107bf0.png)

It's a design behaviour apparently – not one I like though. I really would like to get rid of this enforcement on the user.

Secondarily, I get an error from the FileAdapter, but for that another issue needs to be raised.

**Comment by al-fisher** [comment]
> I really would like to get rid of this enforcement on the user.

Agree - good argument to have a default `Request` that can naturally be over ridden

**Comment by al-fisher** [comment]
For same concrete implementations of Adapters at least

**Comment by alelom** [comment]
Yes – it's something I realised already prior to this issue as I got stuck there myself – I just wonder how many people would get stuck otherwise

**Comment by alelom** [comment]
Raised [issue for the File_Adapter failing to read](https://github.com/BHoM/BHoM_Adapter/issues/111)

**Comment by alelom** [comment]
@michaldengusiak 
By the way, the issue I raised only corrects a secondary behaviour. 
To make this example work for now just remove the `.json` extension at the end of the FileName input.
